name: substitcher
description: opus chaptered audiobook player, encoder and editor with colored subtitle support, basic video editor
publish_to: "none"
version: 26.05.22

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # File system
  file_picker: ^10.3.10
  path_provider: ^2.1.5
  path: ^1.9.0
  crypto: ^3.0.3
  scrollable_positioned_list: ^0.3.8

  # internet
  http: ^1.2.0
  url_launcher: ^6.3.2

  # Device info for Android ABI detection
  device_info_plus: ^12.3.0

  # Process execution (FFmpeg calls)
  process_run: ^1.3.1+1

  # State management
  flutter_riverpod: ^3.2.1
  wakelock_plus: ^1.5.1

  # Audio player
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_linux: ^1.1.4
  media_kit_libs_windows_video: ^1.0.9
  media_kit_libs_android_audio: ^1.1.4

  # UI
  cupertino_icons: ^1.0.9
  shared_preferences: ^2.3.3
  window_manager: ^0.5.1
  package_info_plus: ^9.0.0

  # Character handling for CJK tokenization
  characters: ^1.4.0
  tiny_segmenter_dart: ^1.0.0
  intl: ^0.20.2

  # anki apkg files
  archive: ^4.0.9
  csv: ^8.0.0
  sqlite3: ^3.2.0
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

  macos:
    generate: true
    image_path: "assets/icon.png"

  linux:
    generate: true
    image_path: "assets/icon.png"

  windows:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/adhanclock/
    - assets/lut/

  fonts:
    - family: CustomFonts
      fonts:
        - asset: assets/fonts/0xProto.otf
