class FontAlternatesData {
  static const Map<String, Map<String, String>> anyPosition = {
    'Aloevera': {
      'c': '\u{f020}',
      'e': '\u{f023}',
      'o': '\u{f035}',
      'q': '\u{f037}',
      'v': '\u{f03e}',
      'w': '\u{f040}',
      'x': '\u{f041}',
    },
    'Bentley Vintage': {
      'A': '\u{e019}',
      'K': '\u{e022}',
      'M': '\u{e01d}',
      'R': '\u{e024}',
      'B': '\u{e020}',
      'C': '\u{e002}',
      'D': '\u{e003}',
      'E': '\u{e004}',
      'F': '\u{e005}',
      'G': '\u{e006}',
      'H': '\u{e007}',
      'I': '\u{e008}',
      'J': '\u{e009}',
      'L': '\u{e00B}',
      'N': '\u{e00D}',
      'O': '\u{e098}',
      'P': '\u{e00F}',
      'Q': '\u{e010}',
      'S': '\u{e012}',
      'T': '\u{e013}',
      'U': '\u{e014}',
      'V': '\u{e015}',
      'W': '\u{e016}',
      'X': '\u{e017}',
      'Y': '\u{e018}',
      'k': '\u{e07b}',
      'p': '\u{e07f}',
      's': '\u{e082}',
    },
    'Kambegi': {
      'A': '\u{e11e}',
      'B': '\u{e11f}',
      'D': '\u{e120}',
      'E': '\u{e121}',
      'K': '\u{e122}',
      'L': '\u{e123}',
      'N': '\u{e124}',
      'R': '\u{e125}',
      'X': '\u{e126}',
      'F': '\u{e10b}',
      'H': '\u{e10c}',
      'I': '\u{e10d}',
      'J': '\u{e10e}',
      'M': '\u{e111}',
      'O': '\u{e113}',
      'P': '\u{e114}',
      'Q': '\u{e115}',
      'T': '\u{e117}',
      'U': '\u{e118}',
      'V': '\u{e119}',
      'W': '\u{e11a}',
      'Y': '\u{e11c}',
      'Z': '\u{e11d}',
      'g': '\u{e12a}',
      's': '\u{e143}',
    },
    'Mount Hills': {
      'A': '\u{e052}',
      'B': '\u{e053}',
      'C': '\u{e054}',
      'D': '\u{e055}',
      'E': '\u{e056}',
      'F': '\u{e005}',
      'G': '\u{e006}',
      'H': '\u{e059}',
      'I': '\u{e11c}',
      'J': '\u{e061}',
      'K': '\u{e062}',
      'L': '\u{e063}',
      'M': '\u{e14e}',
      'N': '\u{e12b}',
      'O': '\u{e014}',
      'P': '\u{e12d}',
      'Q': '\u{e016}',
      'R': '\u{e017}',
      'S': '\u{e018}',
      'T': '\u{e019}',
      'U': '\u{e020}',
      'V': '\u{e021}',
      'W': '\u{e022}',
      'X': '\u{e023}',
      'Y': '\u{e024}',
      'Z': '\u{e025}',
      'b': '\u{e027}',
      'd': '\u{e081}',
      'f': '\u{e031}',
      'j': '\u{e035}',
      'o': '\u{e040}',
      's': '\u{e044}',
      'y': '\u{e102}',
    },
  };

  static const Map<String, Map<String, String>> notAtEnd = {
    'Aloevera': {
      'a': '\u{f01d}',
      'd': '\u{f021}',
      'g': '\u{f027}',
      'h': '\u{f029}',
      'j': '\u{f02b}',
      'k': '\u{f02c}',
      'l': '\u{f02e}',
      'm': '\u{f032}',
      'n': '\u{f034}',
      'y': '\u{f042}',
      'z': '\u{f046}',
    },
    'Bentley Vintage': {
      'h': '\u{e078}',
      'm': '\u{e07d}',
      'n': '\u{e07e}',
      'q': '\u{e0b2}',
      'r': '\u{e070}',
      't': '\u{e083}',
      'u': '\u{e084}',
      'v': '\u{e085}',
      'w': '\u{e086}',
      'y': '\u{e065}',
    },
    'Kambegi': {
      'a': '\u{e138}',
      'd': '\u{e131}',
      'h': '\u{e13a}',
      'k': '\u{e13b}',
      'm': '\u{e13c}',
      'n': '\u{e135}',
      'u': '\u{e13e}',
      'x': '\u{e13f}',
    },
    'Mount Hills': {
      'c': '\u{e132}',
      'e': '\u{e134}',
      'q': '\u{e146}',
      'r': '\u{e043}',
      't': '\u{e045}',
      'v': '\u{e047}',
      'w': '\u{e048}',
    },
  };

  static const Map<String, Map<String, String>> onlyAtEnd = {
    'Aloevera': {
      'f': '\u{f025}',
      'g': '\u{f026}',
      'h': '\u{f047}',
      'j': '\u{f02a}',
      'n': '\u{f033}',
      'p': '\u{f036}',
      'r': '\u{f039}',
      's': '\u{f03a}',
    },
    'Bentley Vintage': {
      'a': '\u{e049}',
      'd': '\u{e037}',
      'f': '\u{e038}',
      'g': '\u{e0aa}',
      'm': '\u{e051}',
      'r': '\u{e081}',
      't': '\u{e05d}',
      'y': '\u{e0b9}',
    },
    'Kambegi': {
      'b': '\u{e128}',
      'd': '\u{e129}',
      'e': '\u{e144}',
      'h': '\u{e12b}',
      'k': '\u{e12c}',
      'l': '\u{e12d}',
      'y': '\u{e12e}',
    },
    'Mount Hills': {
      'e': '\u{e108}',
      'h': '\u{e137}',
      'k': '\u{e140}',
      'm': '\u{e142}',
      'n': '\u{e143}',
    },
  };

  static bool hasFontAlternates(String fontName) {
    return anyPosition.containsKey(fontName) ||
           notAtEnd.containsKey(fontName) ||
           onlyAtEnd.containsKey(fontName);
  }
}